package Ricoh6502

import (
	"main/src/cpu/Ricoh6502/enums"
)

type CommandDescription struct {
	Command    byte
	OpcodeName string
	Mode       enums.Modes
	Handler    Handler
}

type Decoder struct {
	Commands []CommandDescription
}

func (c *Decoder) InitCommands() {
	c.Commands = []CommandDescription{
		{Command: 0x98, OpcodeName: "TYA", Mode: enums.ModeIMP, Handler: &TYAHandler{}},
		{Command: 0x20, OpcodeName: "JSR", Mode: enums.ModeABS, Handler: &JSRHandler{}},
		{Command: 0x4C, OpcodeName: "JMP", Mode: enums.ModeABS, Handler: &JMPHandler{}},
		{Command: 0x6C, OpcodeName: "JMP", Mode: enums.ModeIND, Handler: &JMPHandler{}},
		{Command: 0x10, OpcodeName: "BPL", Mode: enums.ModeREL, Handler: &BPLHandler{}},
		{Command: 0x78, OpcodeName: "SEI", Mode: enums.ModeIMP, Handler: &SEIHandler{}},
		{Command: 0xD8, OpcodeName: "CLD", Mode: enums.ModeIMP, Handler: &CLDHandler{}},
		{Command: 0x49, OpcodeName: "EOR", Mode: enums.ModeIMM, Handler: &EORHandler{}},
		{Command: 0x45, OpcodeName: "EOR", Mode: enums.ModeZP, Handler: &EORHandler{}},
		{Command: 0x55, OpcodeName: "EOR", Mode: enums.ModeZPX, Handler: &EORHandler{}},
		{Command: 0x4D, OpcodeName: "EOR", Mode: enums.ModeABS, Handler: &EORHandler{}},
		{Command: 0x5D, OpcodeName: "EOR", Mode: enums.ModeABSX, Handler: &EORHandler{}},
		{Command: 0x59, OpcodeName: "EOR", Mode: enums.ModeABSY, Handler: &EORHandler{}},
		{Command: 0x41, OpcodeName: "EOR", Mode: enums.ModeINDX, Handler: &EORHandler{}},
		{Command: 0x51, OpcodeName: "EOR", Mode: enums.ModeINDY, Handler: &EORHandler{}},
		{Command: 0x29, OpcodeName: "AND", Mode: enums.ModeIMM, Handler: &ANDHandler{}},
		{Command: 0x25, OpcodeName: "AND", Mode: enums.ModeZP, Handler: &ANDHandler{}},
		{Command: 0x35, OpcodeName: "AND", Mode: enums.ModeZPX, Handler: &ANDHandler{}},
		{Command: 0x2D, OpcodeName: "AND", Mode: enums.ModeABS, Handler: &ANDHandler{}},
		{Command: 0x3D, OpcodeName: "AND", Mode: enums.ModeABSX, Handler: &ANDHandler{}},
		{Command: 0x39, OpcodeName: "AND", Mode: enums.ModeABSY, Handler: &ANDHandler{}},
		{Command: 0x21, OpcodeName: "AND", Mode: enums.ModeINDX, Handler: &ANDHandler{}},
		{Command: 0x31, OpcodeName: "AND", Mode: enums.ModeINDY, Handler: &ANDHandler{}},
		{Command: 0x85, OpcodeName: "STA", Mode: enums.ModeZP, Handler: &STAHandler{}},
		{Command: 0x95, OpcodeName: "STA", Mode: enums.ModeZPX, Handler: &STAHandler{}},
		{Command: 0x8D, OpcodeName: "STA", Mode: enums.ModeABS, Handler: &STAHandler{}},
		{Command: 0x9D, OpcodeName: "STA", Mode: enums.ModeABSX, Handler: &STAHandler{}},
		{Command: 0x99, OpcodeName: "STA", Mode: enums.ModeABSY, Handler: &STAHandler{}},
		{Command: 0x81, OpcodeName: "STA", Mode: enums.ModeINDX, Handler: &STAHandler{}},
		{Command: 0x91, OpcodeName: "STA", Mode: enums.ModeINDY, Handler: &STAHandler{}},
		{Command: 0xA9, OpcodeName: "LDA", Mode: enums.ModeIMM, Handler: &LDAHandler{}},
		{Command: 0xA5, OpcodeName: "LDA", Mode: enums.ModeZP, Handler: &LDAHandler{}},
		{Command: 0xB5, OpcodeName: "LDA", Mode: enums.ModeZPX, Handler: &LDAHandler{}},
		{Command: 0xAD, OpcodeName: "LDA", Mode: enums.ModeABS, Handler: &LDAHandler{}},
		{Command: 0xBD, OpcodeName: "LDA", Mode: enums.ModeABSX, Handler: &LDAHandler{}},
		{Command: 0xB9, OpcodeName: "LDA", Mode: enums.ModeABSY, Handler: &LDAHandler{}},
		{Command: 0xA1, OpcodeName: "LDA", Mode: enums.ModeINDX, Handler: &LDAHandler{}},
		{Command: 0xB1, OpcodeName: "LDA", Mode: enums.ModeINDY, Handler: &LDAHandler{}},
		{Command: 0x6A, OpcodeName: "ROR", Mode: enums.ModeAcc, Handler: &RORHandler{}},
		{Command: 0x66, OpcodeName: "ROR", Mode: enums.ModeZP, Handler: &RORHandler{}},
		{Command: 0x76, OpcodeName: "ROR", Mode: enums.ModeZPX, Handler: &RORHandler{}},
		{Command: 0x6E, OpcodeName: "ROR", Mode: enums.ModeABS, Handler: &RORHandler{}},
		{Command: 0x7E, OpcodeName: "ROR", Mode: enums.ModeABSX, Handler: &RORHandler{}},
		{Command: 0xCA, OpcodeName: "DEX", Mode: enums.ModeIMP, Handler: &DEXHandler{}},
		{Command: 0x0A, OpcodeName: "ASL", Mode: enums.ModeAcc, Handler: &ASLHandler{}},
		{Command: 0x06, OpcodeName: "ASL", Mode: enums.ModeZP, Handler: &ASLHandler{}},
		{Command: 0x16, OpcodeName: "ASL", Mode: enums.ModeZPX, Handler: &ASLHandler{}},
		{Command: 0x0E, OpcodeName: "ASL", Mode: enums.ModeABS, Handler: &ASLHandler{}},
		{Command: 0x1E, OpcodeName: "ASL", Mode: enums.ModeABSX, Handler: &ASLHandler{}},
		{Command: 0x4A, OpcodeName: "LSR", Mode: enums.ModeAcc, Handler: &LSRHandler{}},
		{Command: 0x46, OpcodeName: "LSR", Mode: enums.ModeZP, Handler: &LSRHandler{}},
		{Command: 0x56, OpcodeName: "LSR", Mode: enums.ModeZPX, Handler: &LSRHandler{}},
		{Command: 0x4E, OpcodeName: "LSR", Mode: enums.ModeABS, Handler: &LSRHandler{}},
		{Command: 0x5E, OpcodeName: "LSR", Mode: enums.ModeABSX, Handler: &LSRHandler{}},
		{Command: 0x27, OpcodeName: "RLA", Mode: enums.ModeZP, Handler: &RLAHandler{}},
		{Command: 0x37, OpcodeName: "RLA", Mode: enums.ModeZPX, Handler: &RLAHandler{}},
		{Command: 0x2F, OpcodeName: "RLA", Mode: enums.ModeABS, Handler: &RLAHandler{}},
		{Command: 0x3F, OpcodeName: "RLA", Mode: enums.ModeABSX, Handler: &RLAHandler{}},
		{Command: 0x3B, OpcodeName: "RLA", Mode: enums.ModeABSY, Handler: &RLAHandler{}},
		{Command: 0x23, OpcodeName: "RLA", Mode: enums.ModeINDX, Handler: &RLAHandler{}},
		{Command: 0x33, OpcodeName: "RLA", Mode: enums.ModeINDY, Handler: &RLAHandler{}},
		{Command: 0x67, OpcodeName: "RRA", Mode: enums.ModeZP, Handler: &RRAHandler{}},
		{Command: 0x77, OpcodeName: "RRA", Mode: enums.ModeZPX, Handler: &RRAHandler{}},
		{Command: 0x6F, OpcodeName: "RRA", Mode: enums.ModeABS, Handler: &RRAHandler{}},
		{Command: 0x7F, OpcodeName: "RRA", Mode: enums.ModeABSX, Handler: &RRAHandler{}},
		{Command: 0x7B, OpcodeName: "RRA", Mode: enums.ModeABSY, Handler: &RRAHandler{}},
		{Command: 0x63, OpcodeName: "RRA", Mode: enums.ModeINDX, Handler: &RRAHandler{}},
		{Command: 0x73, OpcodeName: "RRA", Mode: enums.ModeINDY, Handler: &RRAHandler{}},
		{Command: 0xE7, OpcodeName: "ISB", Mode: enums.ModeZP, Handler: &ISBHandler{}},
		{Command: 0xF7, OpcodeName: "ISB", Mode: enums.ModeZPX, Handler: &ISBHandler{}},
		{Command: 0xEF, OpcodeName: "ISB", Mode: enums.ModeABS, Handler: &ISBHandler{}},
		{Command: 0xFF, OpcodeName: "ISB", Mode: enums.ModeABSX, Handler: &ISBHandler{}},
		{Command: 0xFB, OpcodeName: "ISB", Mode: enums.ModeABSY, Handler: &ISBHandler{}},
		{Command: 0xE3, OpcodeName: "ISB", Mode: enums.ModeINDX, Handler: &ISBHandler{}},
		{Command: 0xF3, OpcodeName: "ISB", Mode: enums.ModeINDY, Handler: &ISBHandler{}},
		{Command: 0xA2, OpcodeName: "LDX", Mode: enums.ModeIMM, Handler: &LDXHandler{}},
		{Command: 0xA6, OpcodeName: "LDX", Mode: enums.ModeZP, Handler: &LDXHandler{}},
		{Command: 0xB6, OpcodeName: "LDX", Mode: enums.ModeZPY, Handler: &LDXHandler{}},
		{Command: 0xAE, OpcodeName: "LDX", Mode: enums.ModeABS, Handler: &LDXHandler{}},
		{Command: 0xBE, OpcodeName: "LDX", Mode: enums.ModeABSY, Handler: &LDXHandler{}},
		{Command: 0xD0, OpcodeName: "BNE", Mode: enums.ModeREL, Handler: &BNEHandler{}},
		{Command: 0x69, OpcodeName: "ADC", Mode: enums.ModeIMM, Handler: &ADCHandler{}},
		{Command: 0x65, OpcodeName: "ADC", Mode: enums.ModeZP, Handler: &ADCHandler{}},
		{Command: 0x75, OpcodeName: "ADC", Mode: enums.ModeZPX, Handler: &ADCHandler{}},
		{Command: 0x6D, OpcodeName: "ADC", Mode: enums.ModeABS, Handler: &ADCHandler{}},
		{Command: 0x7D, OpcodeName: "ADC", Mode: enums.ModeABSX, Handler: &ADCHandler{}},
		{Command: 0x79, OpcodeName: "ADC", Mode: enums.ModeABSY, Handler: &ADCHandler{}},
		{Command: 0x61, OpcodeName: "ADC", Mode: enums.ModeINDX, Handler: &ADCHandler{}},
		{Command: 0x71, OpcodeName: "ADC", Mode: enums.ModeINDY, Handler: &ADCHandler{}},
		{Command: 0x9A, OpcodeName: "TXS", Mode: enums.ModeIMP, Handler: &TXSHandler{}},
		{Command: 0x60, OpcodeName: "RTS", Mode: enums.ModeIMP, Handler: &RTSHandler{}},
		{Command: 0x90, OpcodeName: "BCC", Mode: enums.ModeREL, Handler: &BCCHandler{}},
		{Command: 0xB0, OpcodeName: "BCS", Mode: enums.ModeREL, Handler: &BCSHandler{}},
		{Command: 0xF0, OpcodeName: "BEQ", Mode: enums.ModeREL, Handler: &BEQHandler{}},
		{Command: 0x24, OpcodeName: "BIT", Mode: enums.ModeZP, Handler: &BITHandler{}},
		{Command: 0x2C, OpcodeName: "BIT", Mode: enums.ModeABS, Handler: &BITHandler{}},
		{Command: 0x30, OpcodeName: "BMI", Mode: enums.ModeREL, Handler: &BMIHandler{}},
		{Command: 0x00, OpcodeName: "BRK", Mode: enums.ModeIMP, Handler: &BRKHandler{}},
		{Command: 0x50, OpcodeName: "BVC", Mode: enums.ModeREL, Handler: &BVCHandler{}},
		{Command: 0x70, OpcodeName: "BVS", Mode: enums.ModeREL, Handler: &BVSHandler{}},
		{Command: 0x18, OpcodeName: "CLC", Mode: enums.ModeIMP, Handler: &CLCHandler{}},
		{Command: 0x58, OpcodeName: "CLI", Mode: enums.ModeIMP, Handler: &CLIHandler{}},
		{Command: 0xB8, OpcodeName: "CLV", Mode: enums.ModeIMP, Handler: &CLVHandler{}},
		{Command: 0xC9, OpcodeName: "CMP", Mode: enums.ModeIMM, Handler: &CMPHandler{}},
		{Command: 0xC5, OpcodeName: "CMP", Mode: enums.ModeZP, Handler: &CMPHandler{}},
		{Command: 0xD5, OpcodeName: "CMP", Mode: enums.ModeZPX, Handler: &CMPHandler{}},
		{Command: 0xCD, OpcodeName: "CMP", Mode: enums.ModeABS, Handler: &CMPHandler{}},
		{Command: 0xDD, OpcodeName: "CMP", Mode: enums.ModeABSX, Handler: &CMPHandler{}},
		{Command: 0xD9, OpcodeName: "CMP", Mode: enums.ModeABSY, Handler: &CMPHandler{}},
		{Command: 0xC1, OpcodeName: "CMP", Mode: enums.ModeINDX, Handler: &CMPHandler{}},
		{Command: 0xD1, OpcodeName: "CMP", Mode: enums.ModeINDY, Handler: &CMPHandler{}},
		{Command: 0xE0, OpcodeName: "CPX", Mode: enums.ModeIMM, Handler: &CPXHandler{}},
		{Command: 0xE4, OpcodeName: "CPX", Mode: enums.ModeZP, Handler: &CPXHandler{}},
		{Command: 0xEC, OpcodeName: "CPX", Mode: enums.ModeABS, Handler: &CPXHandler{}},
		{Command: 0xC0, OpcodeName: "CPY", Mode: enums.ModeIMM, Handler: &CPYHandle{}},
		{Command: 0xC4, OpcodeName: "CPY", Mode: enums.ModeZP, Handler: &CPYHandle{}},
		{Command: 0xCC, OpcodeName: "CPY", Mode: enums.ModeABS, Handler: &CPYHandle{}},
		{Command: 0xC6, OpcodeName: "DEC", Mode: enums.ModeZP, Handler: &DECHandler{}},
		{Command: 0xD6, OpcodeName: "DEC", Mode: enums.ModeZPX, Handler: &DECHandler{}},
		{Command: 0xCE, OpcodeName: "DEC", Mode: enums.ModeABS, Handler: &DECHandler{}},
		{Command: 0xDE, OpcodeName: "DEC", Mode: enums.ModeABSX, Handler: &DECHandler{}},
		{Command: 0x88, OpcodeName: "DEY", Mode: enums.ModeIMP, Handler: &DEYHandler{}},
		{Command: 0xE6, OpcodeName: "INC", Mode: enums.ModeZP, Handler: &INCHandler{}},
		{Command: 0xF6, OpcodeName: "INC", Mode: enums.ModeZPX, Handler: &INCHandler{}},
		{Command: 0xEE, OpcodeName: "INC", Mode: enums.ModeABS, Handler: &INCHandler{}},
		{Command: 0xFE, OpcodeName: "INC", Mode: enums.ModeABSX, Handler: &INCHandler{}},
		{Command: 0xE8, OpcodeName: "INX", Mode: enums.ModeIMP, Handler: &INXHandler{}},
		{Command: 0xC8, OpcodeName: "INY", Mode: enums.ModeIMP, Handler: &INYHandler{}},
		{Command: 0xA0, OpcodeName: "LDY", Mode: enums.ModeIMM, Handler: &LDYHandler{}},
		{Command: 0xA4, OpcodeName: "LDY", Mode: enums.ModeZP, Handler: &LDYHandler{}},
		{Command: 0xB4, OpcodeName: "LDY", Mode: enums.ModeZPX, Handler: &LDYHandler{}},
		{Command: 0xAC, OpcodeName: "LDY", Mode: enums.ModeABS, Handler: &LDYHandler{}},
		{Command: 0xBC, OpcodeName: "LDY", Mode: enums.ModeABSX, Handler: &LDYHandler{}},
		{Command: 0xEA, OpcodeName: "NOP", Mode: enums.ModeIMP, Handler: &NOPHandler{}},
		{Command: 0x09, OpcodeName: "ORA", Mode: enums.ModeIMM, Handler: &ORAHandler{}},
		{Command: 0x05, OpcodeName: "ORA", Mode: enums.ModeZP, Handler: &ORAHandler{}},
		{Command: 0x15, OpcodeName: "ORA", Mode: enums.ModeZPX, Handler: &ORAHandler{}},
		{Command: 0x0D, OpcodeName: "ORA", Mode: enums.ModeABS, Handler: &ORAHandler{}},
		{Command: 0x1D, OpcodeName: "ORA", Mode: enums.ModeABSX, Handler: &ORAHandler{}},
		{Command: 0x19, OpcodeName: "ORA", Mode: enums.ModeABSY, Handler: &ORAHandler{}},
		{Command: 0x01, OpcodeName: "ORA", Mode: enums.ModeINDX, Handler: &ORAHandler{}},
		{Command: 0x11, OpcodeName: "ORA", Mode: enums.ModeINDY, Handler: &ORAHandler{}},
		{Command: 0x48, OpcodeName: "PHA", Mode: enums.ModeIMP, Handler: &PHAHandler{}},
		{Command: 0x08, OpcodeName: "PHP", Mode: enums.ModeIMP, Handler: &PHPHandler{}},
		{Command: 0x68, OpcodeName: "PLA", Mode: enums.ModeIMP, Handler: &PLAHandler{}},
		{Command: 0x28, OpcodeName: "PLP", Mode: enums.ModeIMP, Handler: &PLPHandler{}},
		{Command: 0x2A, OpcodeName: "ROL", Mode: enums.ModeAcc, Handler: &ROLHandler{}},
		{Command: 0x26, OpcodeName: "ROL", Mode: enums.ModeZP, Handler: &ROLHandler{}},
		{Command: 0x36, OpcodeName: "ROL", Mode: enums.ModeZPX, Handler: &ROLHandler{}},
		{Command: 0x2E, OpcodeName: "ROL", Mode: enums.ModeABS, Handler: &ROLHandler{}},
		{Command: 0x3E, OpcodeName: "ROL", Mode: enums.ModeABSX, Handler: &ROLHandler{}},
		{Command: 0x40, OpcodeName: "RTI", Mode: enums.ModeIMP, Handler: &RTIHandler{}},
		{Command: 0xE9, OpcodeName: "SBC", Mode: enums.ModeIMM, Handler: &SBCHandler{}},
		{Command: 0xE5, OpcodeName: "SBC", Mode: enums.ModeZP, Handler: &SBCHandler{}},
		{Command: 0xF5, OpcodeName: "SBC", Mode: enums.ModeZPX, Handler: &SBCHandler{}},
		{Command: 0xED, OpcodeName: "SBC", Mode: enums.ModeABS, Handler: &SBCHandler{}},
		{Command: 0xFD, OpcodeName: "SBC", Mode: enums.ModeABSX, Handler: &SBCHandler{}},
		{Command: 0xF9, OpcodeName: "SBC", Mode: enums.ModeABSY, Handler: &SBCHandler{}},
		{Command: 0xE1, OpcodeName: "SBC", Mode: enums.ModeINDX, Handler: &SBCHandler{}},
		{Command: 0xF1, OpcodeName: "SBC", Mode: enums.ModeINDY, Handler: &SBCHandler{}},
		{Command: 0x38, OpcodeName: "SEC", Mode: enums.ModeIMP, Handler: &SECHandler{}},
		{Command: 0xF8, OpcodeName: "SED", Mode: enums.ModeIMP, Handler: &SEDHandler{}},
		{Command: 0x86, OpcodeName: "STX", Mode: enums.ModeZP, Handler: &STXHandler{}},
		{Command: 0x96, OpcodeName: "STX", Mode: enums.ModeZPY, Handler: &STXHandler{}},
		{Command: 0x8E, OpcodeName: "STX", Mode: enums.ModeABS, Handler: &STXHandler{}},
		{Command: 0x84, OpcodeName: "STY", Mode: enums.ModeZP, Handler: &STYHandler{}},
		{Command: 0x94, OpcodeName: "STY", Mode: enums.ModeZPX, Handler: &STYHandler{}},
		{Command: 0x8C, OpcodeName: "STY", Mode: enums.ModeABS, Handler: &STYHandler{}},
		{Command: 0xAA, OpcodeName: "TAX", Mode: enums.ModeIMP, Handler: &TAXHandler{}},
		{Command: 0xA8, OpcodeName: "TAY", Mode: enums.ModeIMP, Handler: &TAYHandler{}},
		{Command: 0xBA, OpcodeName: "TSX", Mode: enums.ModeIMP, Handler: &TSXHandler{}},
		{Command: 0x8A, OpcodeName: "TXA", Mode: enums.ModeIMP, Handler: &TXAHandler{}},
		{Command: 0x07, OpcodeName: "SLO", Mode: enums.ModeZP, Handler: &SLOHandler{}},
		{Command: 0x17, OpcodeName: "SLO", Mode: enums.ModeZPX, Handler: &SLOHandler{}},
		{Command: 0x0F, OpcodeName: "SLO", Mode: enums.ModeABS, Handler: &SLOHandler{}},
		{Command: 0x1F, OpcodeName: "SLO", Mode: enums.ModeABSX, Handler: &SLOHandler{}},
		{Command: 0x1B, OpcodeName: "SLO", Mode: enums.ModeABSY, Handler: &SLOHandler{}},
		{Command: 0x03, OpcodeName: "SLO", Mode: enums.ModeINDX, Handler: &SLOHandler{}},
		{Command: 0x13, OpcodeName: "SLO", Mode: enums.ModeINDY, Handler: &SLOHandler{}},
		{Command: 0x47, OpcodeName: "SRE", Mode: enums.ModeZP, Handler: &SREHandler{}},
		{Command: 0x57, OpcodeName: "SRE", Mode: enums.ModeZPX, Handler: &SREHandler{}},
		{Command: 0x4F, OpcodeName: "SRE", Mode: enums.ModeABS, Handler: &SREHandler{}},
		{Command: 0x5F, OpcodeName: "SRE", Mode: enums.ModeABSX, Handler: &SREHandler{}},
		{Command: 0x5B, OpcodeName: "SRE", Mode: enums.ModeABSY, Handler: &SREHandler{}},
		{Command: 0x43, OpcodeName: "SRE", Mode: enums.ModeINDX, Handler: &SREHandler{}},
		{Command: 0x53, OpcodeName: "SRE", Mode: enums.ModeINDY, Handler: &SREHandler{}},
	}
}
